apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-core
  namespace: {{ .Values.namespace }}

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-core-env
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-store
  target:
    name: postgres-core-env
    creationPolicy: Owner
  data:
    - secretKey: DB_NAME
      remoteRef:
        key: app/{{ .Values.db.name }}/{{ .Values.env }}
        property: DB_NAME

    - secretKey: DB_USERNAME
      remoteRef:
        key: app/{{ .Values.db.name }}/{{ .Values.env }}
        property: DB_USERNAME

    - secretKey: DB_PASSWORD
      remoteRef:
        key: app/{{ .Values.db.name }}/{{ .Values.env }}
        property: DB_PASSWORD

    - secretKey: DB_TEST_NAME
      remoteRef:
        key: app/{{ .Values.db.name }}/{{ .Values.env }}
        property: DB_TEST_NAME

    - secretKey: DB_TEST_USERNAME
      remoteRef:
        key: app/{{ .Values.db.name }}/{{ .Values.env }}
        property: DB_TEST_USERNAME

    - secretKey: DB_TEST_PASSWORD
      remoteRef:
        key: app/{{ .Values.db.name }}/{{ .Values.env }}
        property: DB_TEST_PASSWORD

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.db.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.db.name }}
    spec:
      serviceAccountName: postgres-core
      containers:
        - name: {{ .Values.db.name }}
          image: "{{ .Values.db.image }}:{{ .Values.db.tag }}"
          imagePullPolicy: "Always"

          env:
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-core-env
                  key: DB_NAME

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-core-env
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-core-env
                  key: DB_PASSWORD

            - name: DB_TEST_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-core-env
                  key: DB_TEST_NAME

            - name: DB_TEST_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-core-env
                  key: DB_TEST_USERNAME

            - name: DB_TEST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-core-env
                  key: DB_TEST_PASSWORD

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-core-env
                  key: DB_PASSWORD

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          volumeMounts:
            - name: {{ .Values.pvc.mount }}
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: {{ .Values.pvc.mount }}
          persistentVolumeClaim:
            claimName: {{ .Values.pvc.claim }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.db.name }}
  ports:
    - name: https
      protocol: TCP
      port: 4430
      targetPort: 5432
    - name: http
      protocol: TCP
      port: 5432
      targetPort: 5432